### ISSUE TITLE
Compiler error CS0618 when using a Nullable object and checking for null

### ISSUE THREAD

**Issue by jflevesque-genetec** [angularsen/UnitsNet#1191]
**Describe the bug**
Having a `Frequency?` or `BitRate?` and checking for null causes error `CS0618` because `operator!=` was marked as deprecated.

**To Reproduce**
1. Add nuget UnitsNet 5.0.0 to a .NET 7.0 project
2. Build using Visual Studio 2022 v17.4.3
3. Use the following snippet
```cs
Frequency? f = null;
if (f != null)
````

Workaround:
```cs
Frequency? f = null;
if (f is not null)
```
This does not trigger the compiler error.

**Expected behavior**
I would expect to be able to check against null with nullable structs.

**Comment by angularsen** [comment]
This is by design. We have had many issues over the years with people trying to compare two quantities they expect to be exactly equal, but run into subtle bugs with rounding errors due to internal conversions with `double` precision. The obsolete warning exists to tell you to use a different `Equals` overload for quantity comparison.

For null checks, you generally are better off using the new `f is not null` syntax.
It ensures you compare against null, and are not invoking any hidden operator overloads that may change the behavior.

The obsolete message could add a hint about the null comparison case.

Does the reasoning make sense?

**Comment by angularsen** [comment]
Suggested fix
https://github.com/angularsen/UnitsNet/pull/1192

**Comment by jflevesque-genetec** [comment]
Yes, I understand the reasoning. With the updated message, it will be obvious how to fix. Thanks!

**Comment by angularsen** [comment]
Great, glad to hear it!
